.catalog:
    name: "Rancer Secrets"
    version: "v1.7.0"
    description: "Volume plugin to fetch and present secrets through files on tmpfs"
    minimum_rancher_version: "v1.7.0"
  upgrade_from: ">v0.0.0"
secrets-driver:
  storage_driver:
    name: rancher-secrets
    description: "A tmpfs driver for secrets"
    scope: local
    create_supported: false
    volume_access_mode: singleHostRW
    volume_capabilities:
      - secrets
    start_on_create: true
