name: healthcheck

on:
  push:
    paths: ["components/healthcheck/**", ".github/workflows/_reusable-go-ci.yml"]
    branches: [main]
  pull_request:
    paths: ["components/healthcheck/**"]

jobs:
  ci:
    uses: ./.github/workflows/_reusable-go-ci.yml
    with:
      component: healthcheck
      image-name: rancher-classic/healthcheck
